// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://qyrqpesspzhqypmmmudl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5cnFwZXNzcHpocXlwbW1tdWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2NzY4NjMsImV4cCI6MjA4MzI1Mjg2M30.7YmLDgwkNak7IqYnFumgD9E_YKTVZV-7EltmFuCbC-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<any>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);
